# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171028_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='cekian',
            name='profile_image',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
